name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # This ensures the job runs on your self-hosted runner

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # You can change this to your preferred Node.js version

    # Install dependencies (if any, modify this step if no dependencies are required)
    - name: Install dependencies
      run: npm install

    # Build application (if applicable, adjust based on your package.json)
    - name: Build application
      run: npm run build  # Adjust this if you do not have a build script in package.json

    # Deploy application (if applicable)
    - name: Deploy
      run: npm run deploy  # Adjust this if you do not have a deploy script in package.json
