name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # This ensures the job runs on your self-hosted runner in Azure

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Change to your desired Node.js version

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run tests (if any)
    - name: Run tests
      run: npm test

    # Build application (if necessary)
    - name: Build application
      run: npm run build  # Adjust based on your package.json scripts

    # Deploy application (if applicable)
    - name: Deploy
      run: npm run deploy  # Adjust based on your package.json scripts
